# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160514_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Product'),
            preserve_default=False,
        ),
    ]
