# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='popular chocolate bar'),
            preserve_default=False,
        ),
    ]
